services:
  postgres:
    image: postgres:15-alpine
    container_name: yt-lang-postgres
    environment:
      POSTGRES_USER: ytlang
      POSTGRES_PASSWORD: ytlang_dev
      POSTGRES_DB: ytlang_db
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ytlang"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: yt-lang-adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    name: yt-lang-postgres-data

networks:
  default:
    name: yt-lang-network
